import EntityPage from "../../components/ui/EntityPage.jsx";
import { formatDateTime } from "../../utils/helpers.js";

export default function HeadSalesReportsPage() {
  return (
    <EntityPage
      title="Reports"
      collection="reports"
      columns={[
        { key: "name", label: "Report" },
        { key: "type", label: "Type" },
        { key: "period", label: "Period" },
        { key: "generatedBy", label: "By" },
        { key: "status", label: "Status" },
        { key: "createdAt", label: "Date", render: (r) => formatDateTime(r.createdAt) },
      ]}
      fields={[
        { name: "name", label: "Report Name", required: true },
        { name: "type", label: "Type", type: "select", options: ["Sales", "Performance", "Revenue", "Forecast"] },
        { name: "period", label: "Period", required: true },
        { name: "generatedBy", label: "Generated By", required: true },
        { name: "status", label: "Status", type: "select", options: ["Generated", "Pending"] },
      ]}
      searchKeys={["name", "type"]}
      defaultValues={{ status: "Generated" }}
      theme="blue"
    />
  );
}
