import { generateId } from "../utils/helpers.js";

const now = () => new Date().toISOString();
const daysAgo = (n) =>
  new Date(Date.now() - n * 86400000).toISOString().slice(0, 10);

export const DEMO_USERS = [
  {
    id: "user-super-admin",
    email: "admin@sfa.com",
    password: "admin123",
    name: "Super Admin",
    role: "SUPER_ADMIN",
    phone: "9876543210",
    employeeId: "EMP001",
    organizationId: "org-1",
    department: "Administration",
    territory: "Global",
    manager: "-",
    status: "Active",
    avatar: null,
    createdAt: now(),
  },
  {
    id: "user-head-sales",
    email: "headsales@sfa.com",
    password: "headsales123",
    name: "Rajesh Kumar",
    role: "HEAD_SALES",
    phone: "9876543211",
    employeeId: "EMP002",
    organizationId: "org-1",
    department: "Sales",
    territory: "National",
    manager: "Super Admin",
    status: "Active",
    avatar: null,
    createdAt: now(),
  },
  {
    id: "user-sales-manager",
    email: "manager@sfa.com",
    password: "manager123",
    name: "Amit Verma",
    role: "SALES_MANAGER",
    phone: "9876543212",
    employeeId: "EMP003",
    organizationId: "org-1",
    department: "Sales",
    territory: "North Zone",
    manager: "Rajesh Kumar",
    status: "Active",
    avatar: null,
    createdAt: now(),
  },
  {
    id: "user-sales-person",
    email: "sales@sfa.com",
    password: "sales123",
    name: "Neha Singh",
    role: "SALES_PERSON",
    phone: "9876543213",
    employeeId: "EMP004",
    organizationId: "org-1",
    department: "Sales",
    territory: "Delhi NCR",
    manager: "Amit Verma",
    status: "Active",
    avatar: null,
    createdAt: now(),
  },
  {
    id: "user-sales-person-2",
    email: "sales2@sfa.com",
    password: "sales123",
    name: "Priya Sharma",
    role: "SALES_PERSON",
    phone: "9876543214",
    employeeId: "EMP005",
    organizationId: "org-1",
    department: "Sales",
    territory: "Mumbai",
    manager: "Amit Verma",
    status: "Active",
    avatar: null,
    createdAt: now(),
  },
];

export const seedDatabase = () => ({
  organizations: [
    {
      id: "org-1",
      name: "ABC Enterprises Pvt Ltd",
      code: "ABC001",
      industry: "FMCG",
      email: "contact@abc.com",
      phone: "011-4567890",
      address: "Connaught Place, New Delhi",
      city: "New Delhi",
      state: "Delhi",
      country: "India",
      status: "Active",
      employees: 250,
      createdAt: now(),
    },
    {
      id: "org-2",
      name: "XYZ Distributors",
      code: "XYZ002",
      industry: "Pharma",
      email: "info@xyz.com",
      phone: "022-1234567",
      address: "Andheri East, Mumbai",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      status: "Active",
      employees: 120,
      createdAt: now(),
    },
  ],
  roles: [
    { id: "role-1", name: "Super Admin", code: "SUPER_ADMIN", permissions: ["all"], status: "Active", users: 1, createdAt: now() },
    { id: "role-2", name: "Head Sales", code: "HEAD_SALES", permissions: ["sales", "reports", "analytics"], status: "Active", users: 1, createdAt: now() },
    { id: "role-3", name: "Sales Manager", code: "SALES_MANAGER", permissions: ["team", "orders", "leads"], status: "Active", users: 1, createdAt: now() },
    { id: "role-4", name: "Sales Person", code: "SALES_PERSON", permissions: ["visits", "orders", "leads"], status: "Active", users: 2, createdAt: now() },
  ],
  users: DEMO_USERS,
  categories: [
    { id: "cat-1", name: "Beverages", code: "BEV", description: "Drinks and beverages", status: "Active", products: 12, createdAt: now() },
    { id: "cat-2", name: "Snacks", code: "SNK", description: "Packaged snacks", status: "Active", products: 18, createdAt: now() },
    { id: "cat-3", name: "Personal Care", code: "PC", description: "Personal care products", status: "Active", products: 8, createdAt: now() },
  ],
  products: [
    { id: "prod-1", name: "Cola 500ml", sku: "COL500", categoryId: "cat-1", category: "Beverages", price: 35, mrp: 40, stock: 500, unit: "Bottle", status: "Active", createdAt: now() },
    { id: "prod-2", name: "Energy Drink", sku: "ENG250", categoryId: "cat-1", category: "Beverages", price: 90, mrp: 99, stock: 300, unit: "Can", status: "Active", createdAt: now() },
    { id: "prod-3", name: "Potato Chips", sku: "CHP100", categoryId: "cat-2", category: "Snacks", price: 20, mrp: 25, stock: 800, unit: "Pack", status: "Active", createdAt: now() },
    { id: "prod-4", name: "Shampoo 200ml", sku: "SHP200", categoryId: "cat-3", category: "Personal Care", price: 180, mrp: 220, stock: 200, unit: "Bottle", status: "Active", createdAt: now() },
  ],
  dealers: [
    { id: "dealer-1", name: "Metro Distributors", code: "DLR001", city: "Delhi", phone: "9811000001", email: "metro@dlr.com", territory: "North", creditLimit: 500000, outstanding: 125000, status: "Active", createdAt: now() },
    { id: "dealer-2", name: "City Wholesale", code: "DLR002", city: "Mumbai", phone: "9811000002", email: "city@dlr.com", territory: "West", creditLimit: 750000, outstanding: 89000, status: "Active", createdAt: now() },
  ],
  customers: [
    { id: "cust-1", name: "Sharma General Store", type: "Retailer", phone: "9811111111", email: "sharma@store.com", address: "Karol Bagh, Delhi", city: "Delhi", assignedTo: "Neha Singh", dealerId: "dealer-1", status: "Active", createdAt: now() },
    { id: "cust-2", name: "Patel Supermarket", type: "Retailer", phone: "9822222222", email: "patel@super.com", address: "Bandra, Mumbai", city: "Mumbai", assignedTo: "Priya Sharma", dealerId: "dealer-2", status: "Active", createdAt: now() },
    { id: "cust-3", name: "Gupta Mart", type: "Retailer", phone: "9833333333", email: "gupta@mart.com", address: "Rohini, Delhi", city: "Delhi", assignedTo: "Neha Singh", dealerId: "dealer-1", status: "Active", createdAt: now() },
  ],
  leads: [
    { id: "lead-1", name: "Kumar Electronics", contact: "Ravi Kumar", phone: "9844444444", email: "ravi@kumar.com", source: "Field Visit", value: 150000, stage: "Qualified", assignedTo: "Neha Singh", territory: "Delhi NCR", status: "Open", createdAt: now() },
    { id: "lead-2", name: "Singh Traders", contact: "Manoj Singh", phone: "9855555555", email: "manoj@singh.com", source: "Referral", value: 85000, stage: "Proposal", assignedTo: "Priya Sharma", territory: "Mumbai", status: "Open", createdAt: now() },
    { id: "lead-3", name: "Reddy Stores Chain", contact: "Suresh Reddy", phone: "9866666666", email: "suresh@reddy.com", source: "Website", value: 320000, stage: "New", assignedTo: "Neha Singh", territory: "Delhi NCR", status: "Open", createdAt: now() },
  ],
  orders: [
    { id: "ord-1", orderNo: "ORD-2026-001", customerId: "cust-1", customer: "Sharma General Store", items: 3, amount: 12500, status: "Delivered", assignedTo: "Neha Singh", orderDate: daysAgo(2), createdAt: now() },
    { id: "ord-2", orderNo: "ORD-2026-002", customerId: "cust-2", customer: "Patel Supermarket", items: 5, amount: 28900, status: "Processing", assignedTo: "Priya Sharma", orderDate: daysAgo(1), createdAt: now() },
    { id: "ord-3", orderNo: "ORD-2026-003", customerId: "cust-3", customer: "Gupta Mart", items: 2, amount: 5600, status: "Pending", assignedTo: "Neha Singh", orderDate: daysAgo(0), createdAt: now() },
  ],
  attendance: [
    { id: "att-1", userId: "user-sales-person", userName: "Neha Singh", date: daysAgo(0), checkIn: "09:02", checkOut: "18:15", status: "Present", location: "Delhi NCR", createdAt: now() },
    { id: "att-2", userId: "user-sales-person-2", userName: "Priya Sharma", date: daysAgo(0), checkIn: "09:30", checkOut: null, status: "Present", location: "Mumbai", createdAt: now() },
    { id: "att-3", userId: "user-sales-person", userName: "Neha Singh", date: daysAgo(1), checkIn: "09:00", checkOut: "18:00", status: "Present", location: "Delhi NCR", createdAt: now() },
  ],
  expenses: [
    { id: "exp-1", userId: "user-sales-person", userName: "Neha Singh", category: "Travel", amount: 850, description: "Cab to Karol Bagh", date: daysAgo(1), status: "Approved", receipt: null, createdAt: now() },
    { id: "exp-2", userId: "user-sales-person", userName: "Neha Singh", category: "Food", amount: 350, description: "Client lunch", date: daysAgo(0), status: "Pending", receipt: null, createdAt: now() },
    { id: "exp-3", userId: "user-sales-person-2", userName: "Priya Sharma", category: "Fuel", amount: 1200, description: "Bike fuel", date: daysAgo(0), status: "Pending", receipt: null, createdAt: now() },
  ],
  visits: [
    { id: "visit-1", userId: "user-sales-person", userName: "Neha Singh", customerId: "cust-1", customer: "Sharma General Store", date: daysAgo(0), checkIn: "10:30", checkOut: "11:15", purpose: "Order Collection", status: "Completed", lat: 28.6517, lng: 77.1909, createdAt: now() },
    { id: "visit-2", userId: "user-sales-person", userName: "Neha Singh", customerId: "cust-3", customer: "Gupta Mart", date: daysAgo(0), checkIn: "14:00", checkOut: null, purpose: "Product Demo", status: "In Progress", lat: 28.7495, lng: 77.0677, createdAt: now() },
    { id: "visit-3", userId: "user-sales-person-2", userName: "Priya Sharma", customerId: "cust-2", customer: "Patel Supermarket", date: daysAgo(0), checkIn: "11:00", checkOut: "12:00", purpose: "Follow Up", status: "Completed", lat: 19.0596, lng: 72.8295, createdAt: now() },
  ],
  routes: [
    { id: "route-1", userId: "user-sales-person", date: daysAgo(0), stops: ["Sharma General Store", "Gupta Mart", "Kumar Electronics"], completed: 1, total: 3, distance: "24 km", status: "In Progress", createdAt: now() },
    { id: "route-2", userId: "user-sales-person-2", date: daysAgo(0), stops: ["Patel Supermarket", "Singh Traders"], completed: 2, total: 2, distance: "18 km", status: "Completed", createdAt: now() },
  ],
  tasks: [
    { id: "task-1", userId: "user-sales-person", title: "Collect payment from Sharma Store", priority: "High", dueDate: daysAgo(0), status: "Pending", createdAt: now() },
    { id: "task-2", userId: "user-sales-person", title: "Submit daily report", priority: "Medium", dueDate: daysAgo(0), status: "Pending", createdAt: now() },
    { id: "task-3", userId: "user-sales-person", title: "Follow up with Reddy Stores", priority: "High", dueDate: daysAgo(1), status: "Completed", createdAt: now() },
  ],
  targets: [
    { id: "tgt-1", userId: "user-sales-person", userName: "Neha Singh", period: "Q2 2026", target: 500000, achieved: 325000, unit: "INR", status: "Active", createdAt: now() },
    { id: "tgt-2", userId: "user-sales-person-2", userName: "Priya Sharma", period: "Q2 2026", target: 450000, achieved: 280000, unit: "INR", status: "Active", createdAt: now() },
    { id: "tgt-3", userId: "user-sales-manager", userName: "Amit Verma", period: "Q2 2026", target: 2000000, achieved: 1250000, unit: "INR", status: "Active", createdAt: now() },
  ],
  approvals: [
    { id: "appr-1", type: "Expense", refId: "exp-2", title: "Client lunch expense", requestedBy: "Neha Singh", amount: 350, status: "Pending", createdAt: now() },
    { id: "appr-2", type: "Expense", refId: "exp-3", title: "Fuel expense", requestedBy: "Priya Sharma", amount: 1200, status: "Pending", createdAt: now() },
    { id: "appr-3", type: "Leave", refId: "leave-1", title: "Leave request - 2 days", requestedBy: "Neha Singh", amount: 0, status: "Approved", createdAt: now() },
  ],
  reports: [
    { id: "rpt-1", name: "Monthly Sales Report", type: "Sales", period: "June 2026", generatedBy: "Rajesh Kumar", status: "Generated", createdAt: now() },
    { id: "rpt-2", name: "Team Performance", type: "Performance", period: "Q2 2026", generatedBy: "Amit Verma", status: "Generated", createdAt: now() },
  ],
  auditLogs: [
    { id: "audit-1", action: "User Login", user: "Super Admin", module: "Auth", details: "Successful login", ip: "192.168.1.1", createdAt: now() },
    { id: "audit-2", action: "Order Created", user: "Neha Singh", module: "Orders", details: "ORD-2026-003 created", ip: "10.0.0.5", createdAt: now() },
    { id: "audit-3", action: "Lead Updated", user: "Priya Sharma", module: "Leads", details: "Lead stage changed to Proposal", ip: "10.0.0.8", createdAt: now() },
  ],
  notifications: [
    { id: "notif-1", userId: "user-sales-person", title: "New lead assigned", message: "Reddy Stores Chain assigned to you", type: "info", read: false, createdAt: now() },
    { id: "notif-2", userId: "user-sales-person", title: "Order approved", message: "Order ORD-2026-001 has been delivered", type: "success", read: false, createdAt: now() },
    { id: "notif-3", userId: "user-sales-manager", title: "Expense pending", message: "2 expense claims need approval", type: "warning", read: false, createdAt: now() },
    { id: "notif-4", userId: "user-super-admin", title: "System update", message: "New analytics module available", type: "info", read: true, createdAt: now() },
  ],
  aiInsights: [
    { id: "ai-1", title: "Revenue Forecast", insight: "Q2 revenue projected to exceed target by 12%", confidence: 87, category: "Revenue", createdAt: now() },
    { id: "ai-2", title: "Lead Conversion", insight: "Delhi NCR leads converting 23% faster than average", confidence: 92, category: "Leads", createdAt: now() },
    { id: "ai-3", title: "Route Optimization", insight: "Neha can save 45 min by reordering today's route", confidence: 78, category: "Operations", createdAt: now() },
  ],
  settings: {
    theme: "light",
    language: "en",
    notifications: { email: true, push: true, sms: false },
    dateFormat: "DD/MM/YYYY",
    currency: "INR",
  },
  userPreferences: {},
  resetTokens: [],
});

export { generateId };
