/**
 * Workflow Event Constants
 *
 * All business events that can trigger workflow automation.
 * Adding a new event: just add a new constant here.
 */

export const WORKFLOW_EVENTS = {
  // Lead Management
  LEAD_QUALIFIED: 'LEAD_QUALIFIED',
  LEAD_ASSIGNED: 'LEAD_ASSIGNED',
  LEAD_STATUS_CHANGED: 'LEAD_STATUS_CHANGED',
  LEAD_CREATED: 'LEAD_CREATED',

  // AI / Campaign
  CAMPAIGN_COMPLETED: 'CAMPAIGN_COMPLETED',

  // CRM / Quotation
  QUOTATION_APPROVED: 'QUOTATION_APPROVED',

  // Sales Order
  SALES_ORDER_CREATED: 'SALES_ORDER_CREATED',
  SALES_ORDER_APPROVED: 'SALES_ORDER_APPROVED',

  // Field Force & Daily Ops
  ATTENDANCE_CHECKED_IN: 'ATTENDANCE_CHECKED_IN',
  ATTENDANCE_CHECKED_OUT: 'ATTENDANCE_CHECKED_OUT',
  VISIT_STARTED: 'VISIT_STARTED',
  VISIT_COMPLETED: 'VISIT_COMPLETED',
  TASK_CREATED: 'TASK_CREATED',
  BEAT_PLAN_APPROVED: 'BEAT_PLAN_APPROVED',
  CALENDAR_EVENT_SCHEDULED: 'CALENDAR_EVENT_SCHEDULED',

  // Task / KPI
  TASK_COMPLETED: 'TASK_COMPLETED',
  TARGET_ACHIEVED: 'TARGET_ACHIEVED',
  TARGET_MISSED: 'TARGET_MISSED',

  // Fulfilment
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  DISPATCH_COMPLETED: 'DISPATCH_COMPLETED',
  MANUFACTURING_COMPLETED: 'MANUFACTURING_COMPLETED',

  // System
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
};

export default WORKFLOW_EVENTS;
