import { useMemo, useState } from "react";
import { FileText, Download, Sparkles, Clock3 } from "lucide-react";
import Button from "../../components/ui/Button.jsx";
import Card from "../../components/ui/Card.jsx";
import { useStorage } from "../../hooks/useLocalStorage.js";
import { formatDateTime, formatCurrency } from "../../utils/helpers.js";

export default function ReportsPage() {
  const { data: reports, create } = useStorage("reports");
  const [selectedType, setSelectedType] = useState("All");

  const filteredReports = useMemo(() => {
    if (selectedType === "All") return reports;
    return reports.filter((report) => report.type === selectedType);
  }, [reports, selectedType]);

  const handleGenerate = () => {
    create({
      name: `Auto-generated ${new Date().toLocaleDateString("en-IN")}`,
      type: "Performance",
      period: "This Week",
      generatedBy: "System",
      status: "Generated",
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col lg:flex-row justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 dark:text-white">Reports</h1>
          <p className="text-sm text-slate-500 mt-1">Generate and review leadership reports across sales and operations.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="secondary" size="sm" onClick={handleGenerate}>Generate report</Button>
          <Button size="sm">Export</Button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="p-5">
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-2xl bg-indigo-500/10 text-indigo-600"><FileText size={20} /></div>
            <div>
              <p className="text-sm text-slate-500">Reports ready</p>
              <p className="text-2xl font-bold text-slate-800 dark:text-white">{reports.length}</p>
            </div>
          </div>
        </Card>
        <Card className="p-5">
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-2xl bg-emerald-500/10 text-emerald-600"><Sparkles size={20} /></div>
            <div>
              <p className="text-sm text-slate-500">AI summaries</p>
              <p className="text-2xl font-bold text-slate-800 dark:text-white">12</p>
            </div>
          </div>
        </Card>
        <Card className="p-5">
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-2xl bg-amber-500/10 text-amber-600"><Clock3 size={20} /></div>
            <div>
              <p className="text-sm text-slate-500">Last sync</p>
              <p className="text-2xl font-bold text-slate-800 dark:text-white">2m ago</p>
            </div>
          </div>
        </Card>
      </div>

      <div className="flex gap-2">
        {['All','Sales','Performance','Financial','Operational'].map((type) => (
          <Button key={type} size="sm" variant={selectedType === type ? 'primary' : 'secondary'} onClick={() => setSelectedType(type)}>{type}</Button>
        ))}
      </div>

      <div className="grid gap-4">
        {filteredReports.map((report) => (
          <Card key={report.id} className="p-5">
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
              <div>
                <div className="flex flex-wrap items-center gap-2">
                  <h2 className="text-lg font-semibold text-slate-800 dark:text-white">{report.name}</h2>
                  <span className="px-2.5 py-1 rounded-full text-xs font-semibold bg-slate-100 text-slate-600">{report.type}</span>
                  <span className="px-2.5 py-1 rounded-full text-xs font-semibold bg-emerald-100 text-emerald-700">{report.status}</span>
                </div>
                <p className="text-sm text-slate-500 mt-2">Period: {report.period} • Generated by {report.generatedBy}</p>
                <p className="text-sm text-slate-500">Created: {formatDateTime(report.createdAt)}</p>
              </div>
              <Button variant="outline" size="sm" icon={Download}>Download</Button>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}
